# Generated by Django 5.1 on 2024-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Последняя дата/время обновления курса"
            ),
        ),
    ]
